# Generated by Django 4.2.6 on 2023-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someone', models.CharField(max_length=50)),
                ('noone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tell', models.CharField(max_length=50)),
            ],
        ),
    ]
